### ISSUE TITLE
IDEA ISSUE 

### ISSUE THREAD

**Issue by Goofybro7** [burnedpopcorn/Sugary-Spire-Web-Port#1]
this is where everyone type what game they want ported i go first 

pizza tower united  (actually online)

**Comment by burnedpopcorn** [comment]
@Goofybro7 

i made a discord server, so you can upload suggestions there

[![Discord Invite Link](https://theprojects.x10.mx/discord.jpg)](https://discord.gg/BJSkBEPU)

**Comment by Goofybro7** [comment]
ok
